[package]
name = "trs"
version = "0.1.1"
authors = ["serbis <Serbis>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
rlua = "0.16.3"
ssh2 = "0.3.3"
termion = "*"
match-downcast = "0.1.2"
rpassword = "3.0.2"
regex = "1"